### ISSUE TITLE
Сервер не проверяет версию схемы БД

### ISSUE THREAD

**Issue by evgeny-osipenko** [aoriens/news-service#1]
Независимо от того, в каком состоянии находится база данных - сервер всё равно запускается и пытается исполнять на ней запросы - если запускать его на пустой БД, или же если вручную поменять запись "schema_version" в таблице config.

Теоретически, это может привести к потере информации, если новую версию сервера запустить на базе, заполненной данными старой версии.

В идеале, основной сервер не должен запускаться на базе, если версия схемы не соответствует ожидаемой - либо выдаётся ошибка, возможно, с инструкциями по тому, как обновить базу до актуальной версии; либо сервер производит обновление самостоятельно, и только после этого начинает обработку запросов.

**Comment by vkpgwt** [comment]
Согласен. Сейчас эта версия схемы только пишется и никем не проверяется. Сделаю простой вариант - только проверку и завершение работы с рекомендацией обновить схему.

**Comment by vkpgwt** [comment]
Исправил в мерже f76d80c33adde699b438748f3d0988ffa1531916 . Правки поделены на коммиты, есть немного рефакторинга.

**Comment by evgeny-osipenko** [comment]
Просмотрел дифф - вроде исправлено.
