### ISSUE TITLE
Использовать квалифицированные импорты или импортировать только нужные функции

### ISSUE THREAD

**Issue by olgaklimenko** [aoriens/news-service#3]

**Comment by vkpgwt** [comment]
Prelude и base это тоже касается? Если нет, какие еще есть исключения из этого правила?

Исправление потребует многих правок и, возможно, переименований. Рассмотрите, пожалуйста, вопрос добавления этого требования в задание 5. Его проще соблюсти, если знать про него заранее. 

Задание 5 ссылается на https://wiki.haskell.org/Programming_guidelines , которая ведет на GHC code style: http://hackage.haskell.org/trac/ghc/wiki/WorkingConventions ->  https://gitlab.haskell.org/ghc/ghc/-/wikis/commentary/coding-style#imports , где сказано:

> **Do not use explicit import lists**, except to resolve name clashes.  There are several reasons for this:
> 
> They slow down development: almost every change is accompanied by an import list change.
> 
> They cause spurious conflicts between developers.
> 
> They lead to useless warnings about unused imports, and time wasted trying to
> keep the import declarations "minimal".
> 
> GHC's warnings are useful for detecting unnecessary imports: see -fwarn-unused-imports.
> 
> TAGS is a good way to find out where an identifier is defined (use hasktags or a similar program in ghc/compiler to generate TAGS file,
> and hit M-. in Emacs; see here for details).

Это противоречит указанию импортировать нужные функции. Остаются только квалифицированные импорты. Как быть с этим?

**Comment by vkpgwt** [comment]
Учитывая совет не использовать explicit import lists, base придется импортировать примерно так:

```
import qualified Data.Maybe as Maybe
...
f :: Maybe.Maybe Int
g x = Maybe.fromMaybe 0 x
```

**Comment by olgaklimenko** [comment]
Переделывать тут не нужно всё, но потом на проектах нужно будет использовать qualified, как в примере выше как раз :) Про противоречие хороший поинт, надо будет нам переработать 5е задание и добавить явные требования по поводу импортов.

**Comment by vkpgwt** [comment]
> Переделывать тут не нужно всё

Тогда где именно переделать? Или вообще не переделывать ничего?

**Comment by olgaklimenko** [comment]
думаю можно вообще не переделывать :)
